### ISSUE TITLE
📓 Дата и время подачи заявки\приглашения пользователя в команду

### ISSUE THREAD

**Issue by picolino** [habralab/garnet-team#109]
### Пользовательская история и сценарии

```
Функция: 
    Я, как пользователь-владелец команды
    Хочу иметь возможность видеть как давно пользователь подал заявку на вступление в команду или как давно висит приглашение пользователя в команду
    Чтобы получить понимание об актуальности заявки\приглашения

    Контекст:
            Допустим существует пользователь 'Вася'
            И существует команда 'FooBar'
            И владельцем команды 'FooBar' является 'Вася'
            И существует пользователь 'Маша'

        Сценарий: Дата и время подачи заявки пользователя на вступление в команду отображается корректно
            Допустим существует заявка на вступление в команду 'FooBar' от пользователя 'Маша' созданная '2023-10-01'
            Когда 'Вася' просматривает заявки на вступление в команду 'FooBar'
            Тогда дата создания первой заявки в списке равна '2023-10-01'

        Сценарий: Дата и время приглашения пользователя в команду отображается корректно
            Допустим существует приглашение пользователя в команду 'FooBar' для пользователя 'Маша' созданное '2023-10-01'
            Когда 'Вася' просматривает приглашения на вступление в команду 'FooBar'
            Тогда дата создания первого приглашения в списке равна '2023-10-01'
``` 

### Дополнительная информация

Реализуем с помощью аудитной информации. Дата подачи заявки\приглашения - равна дате создания заявки\приглашения.

**Comment by gfg7** [comment]
Из-за возможности смены владельца, при которой текущие приглашения в команду **не** сбиваются, считаю, нужно добавить еще от _кого_ было приглашение

**Comment by picolino** [comment]
> Из-за возможности смены владельца, при которой текущие приглашения в команду **не** сбиваются, считаю, нужно добавить еще от _кого_ было приглашение

А подскажи, для какой цели? В каком случае нам важен владелец в приглашении и какие проблемы ты видишь, если при активных приглашениях мы сменим владельца?

**Comment by gfg7** [comment]
Мне кажется, что при их рассмотрение владельцу было бы удобно видеть, что относится к тому, что делал твой предшественник - в особенности, если таких приглашений много
После смены владельца команда может пройти через большие изменения, из-за которых требования, на которые опирались при старых приглашениях, могут быть неактуальны  - нужен способ наглядно показать, что делали до тебя, а потом решать, отменять инвайт или нет
+ это даст плюсики к показу историчности в ui, какой владелец какие решения принимал, пока был в этой роли

Иначе, я не вижу смысла хранить в аудите приглашений пользователя, которым был создан инвайт - мы и так знаем по application слою, что сделать их мог только владелец команды, это happy path

**Comment by picolino** [comment]
Историчность - это отлично
Но в v0.2. Сейчас это не цель

На счет идейки на будущее - запиши в discussions, пожалуйста, интересная мысль
