### ISSUE TITLE
📓 Просмотр количества участников и количества проектов в командах-участниках

### ISSUE THREAD

**Issue by picolino** [habralab/garnet-team#111]
### Пользовательская история и сценарии

```
Функция: 
    Я, как пользователь 
    Хочу иметь возможность посмотреть количество пользователей-участников и количество проектов в командах-участниках в составе просматриваемого проекта
    Чтобы оценить масштаб проекта и силу команд, участвующих в нем

        Контекст:
            Допустим существует проект 'FooBar'
            И существует команда 'DreamTeam'
            И команда 'DreamTeam' является участником проекта 'FooBar'

        Сценарий: Отображение количества участников команды при получении списка команд-участников проекта
            Допустим в команде 'DreamTeam' количество участников равно '2'
            Когда происходит получение списка команд-участников проекта 'FooBar'
            Тогда количество участников в первой команде списка равно '2'

        Сценарий: Отображение количества проектов, в которых участвует команда, при получении списка команд-участников проекта
            Допустим в команде 'DreamTeam' количество проектов равно '1'
            Когда происходит получение списка команд-участников проекта 'FooBar'
            Тогда количество проектов в первой команде списка равно '1'
``` 

### Дополнительная информация

Делаем логику следующим образом:
В сущности `ProjectTeamParticipantDocument` появляется 2 поля-массива: `UserParticipants` и `Projects`. Их и нужно вернуть в ответ на запрос по командам-участникам проекта.

Поле с пользователями должно обновляться из шины сообщений (в команде появился новый участник - добавляем этого пользователя с массив) поле с проектом по аналогии.

Каждый элемент массива - это объект с полями, например по пользователям:
{ UserId, UserName, UserAvatarUrl }.

Не забыть также обработать событие обновления пользователя и обновить аву\ник в этой коллекции

**Comment by picolino** [comment]
Согласен, да, стоит добавить

**Comment by Demorey** [comment]
И еще неоткуда брать изначальный состав команды, тогда в ProjectTeamEntity нужно добавить массив UserParticipants c Id пользователей-участников?

**Comment by gfg7** [comment]
> И еще неоткуда брать изначальный состав команды, тогда в ProjectTeamEntity нужно добавить массив UserParticipants c Id пользователей-участников?

С моей стороны в командах добавлю ивент на принятие нового участника в команду (и выход из состава в дальнейшем)

**Comment by picolino** [comment]
@Demorey Изначальный состав команды ты должен хранить у себя. Получишь ты его из шины сообщений (из событий по добавлению\удалению участников).

Я глянул, сейчас есть 2 типа событий:
- TeamCreatedEvent (создание команды, владелец становится участником команды)
- TeamUserJoinRequestDecidedEvent (решение по заявке на вступление)

Думаю нам нужен еще один тип сообщений, который однозначно определяет, что участник добавлен\удален из команды (в будущем).

Единственное еще у нас не хватает функционала на "отклонение\принятие инвайта пользователя в команду", @gfg7 заведешь задачку на это?

Что-то типа `TeamJoinInviteDecide`

**Comment by gfg7** [comment]
> Единственное еще у нас не хватает функционала на "отклонение\принятие инвайта пользователя в команду", @gfg7 заведешь задачку на это?
> 
> Что-то типа `TeamJoinInviteDecide`

https://github.com/habralab/garnet-team/issues/122
