### ISSUE TITLE
📓 Участникам команды и владельцу проекта приходит уведомление о выходе команды из проекта

### ISSUE THREAD

**Issue by gfg7** [habralab/garnet-team#173]
### Пользовательская история и сценарии

```
Функция: 
    Я, как участник команды или владелец проекта
    Хочу иметь возможность получать уведомления о выходе команды из проекта
    Чтобы быть вовремя осведомленным

        Сценарий: Уведомление о выходе команды из проекта
            Допустим существует пользователь 'Вася'
            И существует проект 'DreamTeam' с владельцем 'Маша'
            И существует команда 'FooBar' с владельцем 'Петя' с участником 'Вася'
            Когда команда 'FooBar' выходит из состава проекта 'DreamTeam'
            Тогда пользователь 'Маша' получает уведомление типа 'TeamLeaveProject' с названием 'Команда покинула проект' и текстом 'Команда 'FooBar' покинула проект  'DreamTeam'' с ссылкой на команду 'FooBar'
           И пользователи 'Петя, Вася' получают уведомление типа 'TeamLeaveProject' с названием 'Команда покинула проект' и текстом 'Команда 'FooBar' покинула проект  'DreamTeam'' с ссылкой на проект 'DreamTeam'
```

### Дополнительная информация

Для обработчика на стороне проектов

 https://github.com/habralab/garnet-team/issues/89#issue-1940693286

**Comment by gfg7** [comment]
Тогда пользователь 'Маша' получает уведомление типа _'TeamLeaveProject' с названием 'Команда покинула проект' и текстом 'Команда 'FooBar' покинула проект  'DreamTeam''_ с ссылкой на команду 'FooBar'
           И пользователи 'Петя, Вася' получают уведомление типа _'TeamLeaveProject' с названием 'Команда покинула проект' и текстом 'Команда 'FooBar' покинула проект  'DreamTeam'' с ссылкой на проект 'DreamTeam'_

TODO:
Разделить типы уведомлений, т.к. разные ссылки
Сделать уникальными названия и текст уведомлений - для команды акцент на решении владельцем, наименования и текст должны различаться у типов для того, чтобы пользователь с командой и проектом мог определить наглядно, с чьей стороны был инициирован выход (в его проекте, или его команды)

**Comment by gfg7** [comment]
https://github.com/habralab/garnet-team/issues/175#issuecomment-1783935403

Аналогично, нужно ли уведомлять остальные команды из проекта? Работают вместе, влияет на совместную деятельность

**Comment by picolino** [comment]
Не нужно
