### ISSUE TITLE
Деплой клиента и сервисов `ory`

### ISSUE THREAD

**Issue by Nelfimov** [habralab/garnet-team#198]
### С чем связан запрос на фичу?

Необходимо пересмотреть роуты и доступ к сервисам.

### Расскажите как вы это себе видите

Для клиента и сервисов `ory` мы предполагаем одну точку входа - через `oathkeeper`. Это единственный сервис который должен быть доступен извне. Его главная функция - определять доступность ресурса пользователю и, соответственно доступу, отправлять. Правила расписаны тут: 

https://github.com/habralab/garnet-team/blob/ee24994576c02be773b6471774865dc0bec33863/config/ory/oathkeeper/access-rules.yaml#L1

Например, неавторизованный пользователь через `oathkeeper` будет всегда перенаправлен на `identity`. Пока он не будет авторизован, доступа к приложению у него не будет.

Необходимо чтобы `oathkeeper` был единственным сервисом, доступном из внешнего контура по индексному роуту. Остальные сервисы - только во внутреннем контуре, так же доступны `oathkeeper`.

### DoD (критерий готовности)

На индексном роуте работает сервис `oathkeeper`. Остальные сервисы недоступны при прямом запросе к ним.

**Comment by picolino** [comment]
То что смогу сделать - настроить единую точку входа из трафика на oathkeeper.
Дальше с конфигурацией и работоспособностью ory придется играться вам самим.

**Comment by Nelfimov** [comment]
> То что смогу сделать - настроить единую точку входа из трафика на oathkeeper.
> Дальше с конфигурацией и работоспособностью ory придется играться вам самим.

Все верно - от тебя только единая точка входа.
