### ISSUE TITLE
Функционал уведомлений на клиенте

### ISSUE THREAD

**Issue by Amiditin** [habralab/garnet-team#258]
### С чем связан запрос на фичу?

Необходимо сверстать по дизайну UI уведомлений и добавить для них запросы

### Расскажите как вы это себе видите

- [x] Поповер с уведомлениями [figma](https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=2800-28725&mode=design&t=oXgzvk1ZXSKRUBm2-4)
- [ ] Запросы на уведомления успешно проходят

### DoD (критерий готовности)

Все элементы UI уведомлений сверстаны по дизайну и запросы проходят успешно

### Приложите пример реализаций

https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368-187&mode=design&t=oXgzvk1ZXSKRUBm2-0

### Приложите материалы задачи

https://stage.garnet.pet-project.habr.com/api/sandbox/

**Comment by Amiditin** [comment]
@Demorey @gfg7

1) Можете добавить `linkedEntityAvatarUrl` и `linkedEntitiesNames` в респонс запроса `notificationsGetListByCurrentUser`?  Необходимо для реализации этого UI [ссылка](https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=2800-29040&mode=dev). В моём предствалении `linkedEntitiesNames` - это массив названий сущностей из `body`, по дизайну у них жирный шрифт. 
2) Сколько всего типов уведомлений? я насчитал 10. Предполагается, что возможно _принять_ или _отклонить_ есть только у `TeamJoinProjectRequest`, `TeamInvite` и `TeamUserJoinRequest`? 
<details>
<summary>Все типы</summary>

`ProjectEditOwner`, `TeamJoinProjectRequest`, `TeamJoinRequestDecide`, `TeamLeaveProject`, `TeamEditOwner`, `TeamInvite`, `TeamInviteDecide`, `TeamParticipantLeaveTeam`, `TeamUserJoinRequest`, `TeamUserJoinRequestDecide`
</details>

3) Для типов `TeamJoinProjectRequest`, `TeamInvite` и `TeamUserJoinRequest` в респонсе нужно получать дополнительно id связанного запроса, чтобы его _отклонить_ или _принять_. Как я понял в текущей реализации поле `linkedEntityId` у этих типов это id команды? Думаю, для этого нужно отдельное поле, чтобы не терять id команды, можете добавить?
4) Также из тестов заметил, что при отправке approve на join request, например `ProjectTeamJoinRequestDecide`, связанное с ним уведомление не удалятся автоматически.

**Comment by gfg7** [comment]
@Amiditin 

> 1. Можете добавить `linkedEntityAvatarUrl` и `linkedEntitiesNames` в респонс запроса `notificationsGetListByCurrentUser`?  Необходимо для реализации этого UI [ссылка](https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=2800-29040&mode=dev). В моём предствалении `linkedEntitiesNames` - это массив названий сущностей из `body`, по дизайну у них жирный шрифт.

ок, добавлю сегодня

> 2. Сколько всего типов уведомлений? я насчитал 10. Предполагается, что возможно _принять_ или _отклонить_ есть только у `TeamJoinProjectRequest`, `TeamInvite` и `TeamUserJoinRequest`?
> 
> Все типы

да, вроде, все

> 3. Для типов `TeamJoinProjectRequest`, `TeamInvite` и `TeamUserJoinRequest` в респонсе нужно получать дополнительно id связанного запроса, чтобы его _отклонить_ или _принять_. Как я понял в текущей реализации поле `linkedEntityId` у этих типов это id команды? Думаю, для этого нужно отдельное поле, чтобы не терять id команды, можете добавить?

делалось до дизайна уведомлений, ожидали просто переход на страницу команды  с открытым списком заявок , поправлю

> 4. Также из тестов заметил, что при отправке approve на join request, например `ProjectTeamJoinRequestDecide`, 
связанное с ним уведомление не удалятся автоматически. Это баг?

забыли по decide, в командах тоже только по cancel вижу, добавим
