### ISSUE TITLE
Функционал страницы команд проекта на клиенте

### ISSUE THREAD

**Issue by Amiditin** [habralab/garnet-team#259]
### С чем связан запрос на фичу?

Необходимо сверстать по дизайну UI страницы команд проекта и добавить для них запросы

### Расскажите как вы это себе видите

- [x] Страница команд проекта [figma](https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=2786-26927&mode=design&t=oXgzvk1ZXSKRUBm2-4)
- [x] Запросы на управление командами проекта успешно проходят
- [x] Модальное окно пригласить команду в проект [figma](https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=2788-28639&mode=dev)
 
### DoD (критерий готовности)

Все элементы UI страницы команд проекта сверстаны по дизайну и запросы проходят успешно

### Приложите пример реализаций

https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368-187&mode=design&t=oXgzvk1ZXSKRUBm2-0

### Приложите материалы задачи

https://stage.garnet.pet-project.habr.com/api/sandbox/

**Comment by Amiditin** [comment]
@gfg7 
Для отправки запроса на вступление команды в проект, по идее, используется запрос `teamJoinProjectRequest`, но, если смотреть по схеме, то у него какой-то `input` странный:
```
mutation TeamJoinProjectRequest($id: String!, $teamId: String!, $projectId: String!) {
  teamJoinProjectRequest(
    input: { input: { id: $id, projectId: $projectId, teamId: $teamId } }
  ) {
    id
  }
}
``` 
Мне кажется должно быть что-то такое:
```
mutation TeamJoinProjectRequest($projectId: String!, $teamId: String!) {
  teamJoinProjectRequest(input: { projectId: $projectId, teamId: $teamId }) {
    id
  }
}
```

**Comment by Amiditin** [comment]
@gfg7 
Также, можете добавить в `projectTeamJoinRequestsByProjectId` дополнительную информацию о команде: `description`, `avatarUrl`, `projectCount` и `teamParticipants`. Необходимо для этого UI элемента [ссылка](https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=2786-26934&mode=dev).

**Comment by Amiditin** [comment]
@Demorey 
Запрос `projectTeamJoinRequestsByProjectId` возвращает ошибку, если в респонсе запросить `teamDescription`:

<details>
<summary>Запрос</summary>
```
query ProjectTeamJoinRequestsByProjectId($id: String!) {
  projectTeamJoinRequestsByProjectId(input: { projectId: $id }) {
    projectTeamJoinRequest {
      id
      projectId
      teamId
      teamName
      teamDescription
      teamAvatarUrl
      projectCount
      teamUserParticipants
    }
  }
}

{
 "id": "6565ea4f25228e50861e89d2" 
}
```
</details>

**Comment by Demorey** [comment]
> @Demorey Запрос `projectTeamJoinRequestsByProjectId` возвращает ошибку, если в респонсе запросить `teamDescription`:
> 
> Запрос

А какая именно ошибка выходит? Я делаю запрос и ошибка не воспроизводится
![Screenshot 2023-11-28 190817](https://github.com/habralab/garnet-team/assets/63935188/5a4ebe2f-e8cc-44b2-922c-79a9efc754d8)

**Comment by Amiditin** [comment]
> > @Demorey Запрос `projectTeamJoinRequestsByProjectId` возвращает ошибку, если в респонсе запросить `teamDescription`:
> > Запрос
> 
> А какая именно ошибка выходит? Я делаю запрос и ошибка не воспроизводится ![Screenshot 2023-11-28 190817]

@Demorey  Попробуй добавить requests для проекта, чтобы массив не пустой был.

```
mutation TeamJoinProjectRequest($teamId: String!, $projectId: String!) {
  teamJoinProjectRequest(input: { projectId: $projectId, teamId: $teamId }) {
    id
  }
}
```

**Comment by gfg7** [comment]
> @gfg7 Для отправки запроса на вступление команды в проект, по идее, используется запрос `teamJoinProjectRequest`, но, если смотреть по схеме, то у него какой-то `input` странный:
> 
> ```
> mutation TeamJoinProjectRequest($id: String!, $teamId: String!, $projectId: String!) {
>   teamJoinProjectRequest(
>     input: { input: { id: $id, projectId: $projectId, teamId: $teamId } }
>   ) {
>     id
>   }
> }
> ```
> 
> Мне кажется должно быть что-то такое:
> 
> ```
> mutation TeamJoinProjectRequest($projectId: String!, $teamId: String!) {
>   teamJoinProjectRequest(input: { projectId: $projectId, teamId: $teamId }) {
>     id
>   }
> }
> ```

вмержено
