### ISSUE TITLE
Экран регистрации, входа и онбординга

### ISSUE THREAD

**Issue by dimabeat** [habralab/garnet-team#28]
### С чем связан запрос на фичу?

Необходимо описать процесс регистрации, входа и онбординга пользователя на платформу

### Расскажите как вы это себе видите

Пользователь регистрируется:
заполняет поля - Имя, Фамилия, Email, Пароль, Повторить пароль.

Пользователь входит на сайт под своими доступами:
заполняет поля - Email, Пароль
может запросить восстановление пароля.

Пользователь проходит онбординг внося свои данные:
- Аватар
- Информацию о себе
- Свои навыки.

### DoD (критерий готовности)

Экраны, которые подробно раскрывают процесс регистрации, входа и онбординга

**Comment by dimabeat** [comment]
Экран регистрации, входа и онбординга - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=VN1H8J4RhLRa4guN-1

**Comment by TorinAsakura** [comment]
> Экран регистрации, входа и онбординга - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=VN1H8J4RhLRa4guN-1

1. Наведите порядок в структуре экранов
2. Не вижу состояний экрана при различных сценариях взаимодействия
3. https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368-216&mode=design&t=dVI9o5dOwC1FAlq2-4 - не нужна
4. Откуда у тебя взялось навигационное меню если у пользователя ещё нет прав его видеть?
5. Оформите страницу в соответствии с нашим стилем
6. Почему на странице идентификации пользователя присутствуют другие сценарии?

**Comment by TorinAsakura** [comment]
Если профиль тоже относится к онбордингу - то я рекомендую вернуть тот шаблон, что мы делали со мной

**Comment by dimabeat** [comment]
> > Экран регистрации, входа и онбординга - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=VN1H8J4RhLRa4guN-1
> 
> 1. Наведите порядок в структуре экранов
> 2. Не вижу состояний экрана при различных сценариях взаимодействия
> 3. https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368-216&mode=design&t=dVI9o5dOwC1FAlq2-4 - не нужна
> 4. Откуда у тебя взялось навигационное меню если у пользователя ещё нет прав его видеть?
> 5. Оформите страницу в соответствии с нашим стилем
> 6. Почему на странице идентификации пользователя присутствуют другие сценарии?

1. Готово
2. Готово
3. Как пользователь узнает, что он зарегистрировался и перейдет ко входу?
4. Готово
5. Готово
6. Готово

> Если профиль тоже относится к онбордингу - то я рекомендую вернуть тот шаблон, что мы делали со мной

Вынесено на отдельную страницу - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=281%3A62&mode=design&t=WrmNzCg9DYT51LvX-1. Шаболон восстановлен.

**Comment by dimabeat** [comment]
Внесли правки - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=4NzXE9NjzDwsgYTs-1

**Comment by TorinAsakura** [comment]
> Внесли правки - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=4NzXE9NjzDwsgYTs-1

Принято.
