### ISSUE TITLE
Экраны проекта

### ISSUE THREAD

**Issue by dimabeat** [habralab/garnet-team#29]
### С чем связан запрос на фичу?

Для взаимодействия с сущностью «Проект» необходимо описать бизнес-процесс вокруг её сущности

### Расскажите как вы это себе видите

**Создатель команды** 
что видит:
- Аватар проекта
- Название проекта
- Описание проекта
- Необходимые специализации
- Участники проекта

что может делать:
- Пригласить/удалить участника
- Сменить владельца
- Удалить
- Редактировать информацию

**Участник проекта**
что видит:
- Аватар проекта
- Название проекта
- Описание проекта
- Необходимые специализации
- Участники проекта

что может делать:
- Подать заявку/выйти из проекта

### DoD (критерий готовности)

Экраны, которые подробно раскрывают процесс работы сущности

### Приложите материалы задачи

https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=281%3A62&mode=design&t=VN1H8J4RhLRa4guN-1

**Comment by TorinAsakura** [comment]
1. Экраны не на своей странице
2. Нарушение бизнес-логики - проект не может быть создан без команды
3. Нет детализации сценариев/фрагментов
4. Использование слайдсета как антипаттерн на экране с большим количеством объектных групп взаимодействия

**Comment by picolino** [comment]
> 2. Нарушение бизнес-логики - проект не может быть создан без команды

В соответствии с бизнес-логикой проект может быть создан без команды

Пользователь может создать проект, после создания у него нет команд-участников, но есть овнер - пользователь, создавший проект.

А вот присоединиться к участию в проекте могут только команды

**Comment by dimabeat** [comment]
> 1. Экраны не на своей странице
> 2. Нарушение бизнес-логики - проект не может быть создан без команды
> 3. Нет детализации сценариев/фрагментов
> 4. Использование слайдсета как антипаттерн на экране с большим количеством объектных групп взаимодействия

1. Готово
2. -
3. Вынесено во фрагменты, доступно в вариантах
4. Готово
5. Готово

**Comment by dimabeat** [comment]
Внесли правки - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=4NzXE9NjzDwsgYTs-1

**Comment by TorinAsakura** [comment]
> Внесли правки - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A187&mode=design&t=4NzXE9NjzDwsgYTs-1

я просил убрать сценарии либо на отдельную страницу либо вообще отказаться от них. Зачем они?

**Comment by TorinAsakura** [comment]
Проблемы в переиспользовании компонентной базы, опять.

**Comment by dimabeat** [comment]
> Проблемы в переиспользовании компонентной базы, опять.

Исправлено

**Comment by TorinAsakura** [comment]
Approved
