### ISSUE TITLE
Презентация

### ISSUE THREAD

**Issue by Exanngell** [habralab/garnet-team#56]
### С чем связан запрос на фичу?

Необходимо создать презентацию к выступлению к 10.10

### Расскажите как вы это себе видите

1) Написать план выступления
2) Написать сценарий о чем говорить
3) Подобрать референсы к визуальной части презентации
4) Собрать макет презентации

### DoD (критерий готовности)

Готовая презентация в figma

### Приложите пример реализаций

https://www.behance.net/gallery/171110465/CRM-system?tracking_source=search_projects%7Cпрезентация+CRM 

### Приложите материалы задачи

https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=791%3A8965&mode=design&t=yjuNdo2I9AhBsWfI-1

**Comment by Exanngell** [comment]
План:
1) что мы за команда, кто сегодня выступает
2)про проект - кратко, чтобы напомнить. задачи, которые мы решали
3)как выстраивался дизайн-процесс
4)два пользователя: андрей и маша
5)информационная архитектура (бизнес-процессы)?
6)анимационные прототипы для показа работы сценариев (возьмем основные)
7) экраны с пояснениями
8) дизайн кит, цвета, шрифты, сетка
9) с какими проблемами мы столкнулись (нужно ли?)
10)следите дальше, впереди много интересного

**Comment by TorinAsakura** [comment]
> План:
> 
> 1. что мы за команда, кто сегодня выступает
> 2. про проект - кратко, чтобы напомнить. задачи, которые мы решали
> 3. как выстраивался дизайн-процесс
> 4. два пользователя: андрей и маша
> 5. информационная архитектура (бизнес-процессы)?
> 6. прототипы для показа работы сценариев (возьмем основные)
> 7. экраны с пояснениями
> 8. дизайн кит, цвета, шрифты, сетка
> 9. с какими проблемами мы столкнулись (нужно ли?)
> 10. следите дальше, впереди много интересного

4. Что за Андрей и Маша? Что там у них за сценарии пользования? Можно где-то подсмотреть ваш CJM?

**Comment by Exanngell** [comment]
> > План:
> > 
> > 4. два пользователя: андрей и маша
> 
> 4. Что за Андрей и Маша? Что там у них за сценарии пользования? Можно где-то подсмотреть ваш CJM?

Перед тем как начать делать прототипы, была собрана такая штука. На ее основе можно сделать визуализацию сценария. CJM у нас нет. https://www.figma.com/file/29OhoYozE6cuGM5JJOcJON/%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-GARNet?type=whiteboard&node-id=0%3A1&t=mvpUrcgPQJy97JTr-1

**Comment by Exanngell** [comment]
> > 6. прототипы для показа работы сценариев (возьмем основные)
> 
> Что есть "основные"?
> 
Покажем два сценария: 
от входа до создание команды, создание проекта - 1 
от профиля до отправки заявки в команду - 2

то есть в режиме интерактива пройдем путь Маши и Андрея с пояснениями.

**Comment by Exanngell** [comment]
> > 7. экраны с пояснениями
> 
> Нужны рефы, надо понимать как эти экраны будут выглядеть

Хочу, чтобы мы показали уникальность нашего продукта не в текстовом формате, а как это было реализовано с помощью дизайна. Скрины: пример и компонент нашего продукта, который действительно интересно выглядит и его можно не заметить на общих экранах. Если будет анимация - ее тоже нужно показать, создать интерес у слушателей, а не просто болтать о проделанной работе.

![image](https://github.com/habralab/garnet-team/assets/146862690/4802df17-bfed-440b-8508-c76aada7fec7)
![image](https://github.com/habralab/garnet-team/assets/146862690/deae5476-95f1-49a9-9442-63e36bdb0a50)

**Comment by Exanngell** [comment]
> > 9. с какими проблемами мы столкнулись (нужно ли?)
> 
> Обязательно)

Пропишем 

> > 10. следите дальше, впереди много интересного
> 
> Coming soon типа?
да, чтобы продолжали следить за нами и голосовали. Типа призыва к действию

**Comment by TorinAsakura** [comment]
> > > 7. экраны с пояснениями
> > 
> > 
> > Нужны рефы, надо понимать как эти экраны будут выглядеть
> 
> Хочу, чтобы мы показали уникальность нашего продукта не в текстовом формате, а как это было реализовано с помощью дизайна. Скрины: пример и компонент нашего продукта, который действительно интересно выглядит и его можно не заметить на общих экранах. Если будет анимация - ее тоже нужно показать, создать интерес у слушателей, а не просто болтать о проделанной работе.
> 
> ![image](https://user-images.githubusercontent.com/146862690/272341865-4802df17-bfed-440b-8508-c76aada7fec7.png) ![image](https://user-images.githubusercontent.com/146862690/272342199-deae5476-95f1-49a9-9442-63e36bdb0a50.png)

вот для этого ты должна будешь собрать нам муд/рефборд

**Comment by Exanngell** [comment]
3. Рефы подобраны https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=845%3A19751&mode=design&t=S0MAmGP1uEfoqK9O-1

**Comment by TorinAsakura** [comment]
> 2. Сценарий прописан по слайдам. Эскизы готовы. Будет правиться по мере наполнения. (паралельно с этой таской [Визуальное оформление #60](https://github.com/habralab/garnet-team/issues/60) ) https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=795%3A7730&mode=design&t=S0MAmGP1uEfoqK9O-1

полагаю это дело необходимо структурировать, ибо сейчас мало что понятно

**Comment by TorinAsakura** [comment]
> 3. Рефы подобраны https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=845%3A19751&mode=design&t=S0MAmGP1uEfoqK9O-1

Качество получше бы( Ничего не вижу
![Снимок экрана 2023-10-05 в 00 53 58](https://github.com/habralab/garnet-team/assets/3940885/560a63a3-7d9a-4212-a52e-a43bb0640786)
