### ISSUE TITLE
Визуальное оформление

### ISSUE THREAD

**Issue by Exanngell** [habralab/garnet-team#60]
### С чем связан запрос на фичу?

Нужно создать визуальное оформление

### Расскажите как вы это себе видите

1) поиск референсов, создание мудборда
2) Создание ui kit,
3) Дизайн-оформление страниц
4) Подготовка макетов к презентации

### DoD (критерий готовности)

Готовое визуальное оформление в figma

### Приложите пример реализаций

https://www.figma.com/file/qlXF0YWpQkEKBPYox7p69V/Material-2-Design-Kit-(Community)?type=design&node-id=0-2347&mode=design&t=KXMgaJrKJ71xlHmF-0 

### Приложите материалы задачи

https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=823%3A12373&mode=design&t=S0MAmGP1uEfoqK9O-1

**Comment by Exanngell** [comment]
1) Готово. https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A186&mode=design&t=S0MAmGP1uEfoqK9O-1

**Comment by TorinAsakura** [comment]
> 1. Готово. https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A186&mode=design&t=S0MAmGP1uEfoqK9O-1

оставил комментарии, нужно больше рефов, собери борду небольшую на бихансе, нужна выборка из 15-20 ресурсов

**Comment by dimabeat** [comment]
> > 1. Готово. https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=368%3A186&mode=design&t=S0MAmGP1uEfoqK9O-1
> 
> оставил комментарии, нужно больше рефов, собери борду небольшую на бихансе, нужна выборка из 15-20 ресурсов

https://www.behance.net/collection/207350185/GARNet

**Comment by dimabeat** [comment]
@TorinAsakura ui-кит, стили - https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=823%3A12373&mode=design&t=JZkfBFvQsjF80TWy-1

**Comment by TorinAsakura** [comment]
1. Нужен ещё экран с иконками
2. Нет общих для системы фрагментов - мастхэв
3. https://www.google.com/search?q=garnet+logo&newwindow=1&client=safari&sca_esv=571399955&rls=en&tbm=isch&sxsrf=AM9HkKnbic0AzxmBMUWznPshfUA4rOnjfQ:1696632706128&source=lnms&sa=X&ved=2ahUKEwioi42uweKBAxV_IRAIHfnHADcQ_AUoAXoECAIQAw&biw=1647&bih=1363&dpr=1 - идеи для лого
4. Перенесите из uikit'a всё на страницу компонентов, вообще не понимаю откуда вы это взяли
5. Начинайте пересобирать экраны на базе компонентов

**Comment by dimabeat** [comment]
> 1. Нужен ещё экран с иконками
> 2. Нет общих для системы фрагментов - мастхэв
> 3. https://www.google.com/search?q=garnet+logo&newwindow=1&client=safari&sca_esv=571399955&rls=en&tbm=isch&sxsrf=AM9HkKnbic0AzxmBMUWznPshfUA4rOnjfQ:1696632706128&source=lnms&sa=X&ved=2ahUKEwioi42uweKBAxV_IRAIHfnHADcQ_AUoAXoECAIQAw&biw=1647&bih=1363&dpr=1 - идеи для лого
> 4. Перенесите из uikit'a всё на страницу компонентов, вообще не понимаю откуда вы это взяли
> 5. Начинайте пересобирать экраны на базе компонентов

1. Иконки добавлены
2. Каких именно?
3. Ок
4. Перенесли
5. Ок, приступили

**Comment by dimabeat** [comment]
сделал еще фрагменты, начал накидывать собирать экраны (в драфтах) https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=952%3A38201&mode=design&t=YR7Y6Gq1lzA79LQL-1

**Comment by Exanngell** [comment]
https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=952%3A38164&mode=design&t=EMgRwqDgvEpCTi7K-1

**Comment by TorinAsakura** [comment]
> сделал еще фрагменты, начал накидывать собирать экраны (в драфтах) https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=952%3A38201&mode=design&t=YR7Y6Gq1lzA79LQL-1

не нужно в драфты класть, делай сразу на страницах

далее - не увидел фрагментов

**Comment by TorinAsakura** [comment]
> сделал еще фрагменты, начал накидывать собирать экраны (в драфтах) https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=952%3A38201&mode=design&t=YR7Y6Gq1lzA79LQL-1

оставил комменты

**Comment by dimabeat** [comment]
> > сделал еще фрагменты, начал накидывать собирать экраны (в драфтах) https://www.figma.com/file/Ej5wvzeEHOcgkXCerWJQj6/Garnet-Service?type=design&node-id=952%3A38201&mode=design&t=YR7Y6Gq1lzA79LQL-1
> 
> оставил комменты

там выше, над прототипами уже в дизайне экраны

**Comment by TorinAsakura** [comment]
Визуал принят
